
server:
  # 项目运行端口号（访问地址如 http://localhost:5051）
  port: 9090
  servlet:
    # 项目的统一访问前缀路径，比如访问接口时是 /api/xxx
    context-path: /api
ws:
  port: 9091
# ===============================
#  上传文件配置
# ===============================
spring:
  application:
    name: NoriChat
  servlet:
    multipart:
      # 单个文件最大大小
      max-file-size: 15MB
      # 总请求大小限制（多文件一起上传时）
      max-request-size: 15MB

  # ===============================
  # 数据库配置（MySQL）
  # ===============================
  datasource:

    # 数据库连接地址（注意修改库名和时区）
    url: jdbc:mysql://localhost:3306/norichat?autoConnect=true&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    # 数据库用户名
    username: root
    # 数据库密码
    password: kevin2517.
    # MySQL 驱动类（MySQL 8.x 使用 com.mysql.cj.jdbc.Driver）
    driver-class-name: com.mysql.cj.jdbc.Driver
    # Hikari 连接池配置（Spring Boot 默认使用 HikariCP）
    hikari:
      # 最小空闲连接数（系统保持这么多连接可用）
      minimum-idle: 5
      # 最大连接数（高并发时的上限）
      maximum-pool-size: 10
      # 空闲连接超时时间（单位：毫秒）
      idle-timeout: 180000
      # 连接最长生命周期（超过会被回收）
      max-lifetime: 1800000
      # 连接超时时间（获取连接超时）
      connection-timeout: 30000

  # ===============================
  #  Redis 配置（如果项目用到了缓存）
  # ===============================
  redis:
    spring:
      data:
        redis:
          # Redis 主机地址
          host: 127.0.0.1
          # Redis 端口号
          port: 6379
          # 使用的数据库（默认 0）
          database: 0
          # 如果有密码，可加上：
          # password: yourpassword
  mail:
    host: smtp.qq.com          # 163: smtp.163.com  Gmail: smtp.gmail.com
    port: 465                  # 465 SSL / 587 STARTTLS
    username: 2035098108@qq.com    # 你的发件邮箱
    password: prizztrqkiikecdf     # 邮箱“授权码”
    protocol: smtps            # 465 用 smtps；如用 587：protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
          starttls.required: true
        debug: false           # 调试打开 true 可看详细日志
from:
  mail: 2035098108@qq.com          # 作为默认发件人

mybatis:
  configuration:
    #打印 sql 告诉 MyBatis “用 SLF4J 打日志”
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  #MyBatis 会自动扫描这个包下所有类，就是用来写sql的xml
  mapper-locations: classpath:mappers/*.xml
  #MyBatis 会自动扫描这个包下所有类,省的parameterType路径过长如io.github.kevvy.chat_java.entity.User
  type-aliases-package: io.github.kevvy.chat_java.entity

project:
  folder: ./NoriChat/WebSer/

log:
  root:
    level: DEBUG
    #level: INFO
    path: ./logs/NoriChat

#超级管理员
admin:
  email: 2035098108@qq.com

#是否开发模式
dev: false

jwt:
  secret: KevvySecretKey-K3vvyS3cur3Key-ForJWT!!
  expire-time: 86400000  # token有效期（毫秒）这里是24小时





